<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="XTI_Core.Fakes" Version="1.10.26-dev260424141958857" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XTI_TempLog\XTI_TempLog.csproj" />
	</ItemGroup>

</Project>
